# Generated by Django 5.2.17 on 2026-10-10 02:31

import pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_application_company_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='listing_url',
            field=models.TextField(blank=True, validators=[pipeline.models.AnyLengthURLValidator()]),
        ),
    ]
